SoccerClubManagementSystem/Models/Club.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SoccerClubManagementSystem.Models
{
    //This is Club Model
    public class Club
    {
        public int ClubId { get; set; }
        public string ClubName { get; set; }
        public string ClubAddress { get; set; }
        public string Clubcontact { get; set; }
        public string ClubEmail { get; set; }
        public string ClubContactPerson { get; set; }
        public string ClubCity { get; set; }
    }
}

SoccerClubManagementSystem/Models/ClubRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SoccerClubManagementSystem.Models
{
    //This is ClubRepository 
    public class ClubRepository
    {

        List<Club> Clublist = new List<Club>();
        public ClubRepository()
        { 
            //Filling Initial data and Used session to 
            //maintain data between two request
            List<Club> lst = (List<Club>)HttpContext.Current.Session["clb"];
            if (lst == null)
            {
                Clublist.Add(new Club { ClubId = 101, ClubName = "Raj Path", ClubAddress = "H.G Highway Ahmedabad", Clubcontact = "917391390", ClubEmail = "test@rajpath.com", ClubContactPerson = "Jimmy", ClubCity = "Ahmedabad" });
                Clublist.Add(new Club { ClubId = 102, ClubName = "Silver", ClubAddress = "Gota Cross Raod", Clubcontact = "817391390", ClubEmail = "test@silver.com", ClubContactPerson = "nimesh", ClubCity = "Ahmedabad" });
                Clublist.Add(new Club { ClubId = 102, ClubName = "Alpha", ClubAddress = "London Cross Raod", Clubcontact = "717391397", ClubEmail = "test@silver.com", ClubContactPerson = "Jigar", ClubCity = "London" });
                Clublist.Add(new Club { ClubId = 102, ClubName = "Gujarat", ClubAddress = "Vijay Cross Raod", Clubcontact = "917891390", ClubEmail = "test@silver.com", ClubContactPerson = "Nelson", ClubCity = "Delhi" });
                Clublist.Add(new Club { ClubId = 102, ClubName = "Potter", ClubAddress = "Gota Cross Raod", Clubcontact = "918391398", ClubEmail = "test@silver.com", ClubContactPerson = "ritika", ClubCity = "Auuckland" });
                HttpContext.Current.Session["clb"] = Clublist;
            }
        }
        public IEnumerable<Club> GetClubs()
        {
            List<Club> lst = (List<Club>)HttpContext.Current.Session["clb"];

            return lst;
        }
        public Club GetClubByID(int id)
        {
            List<Club> lst = (List<Club>)HttpContext.Current.Session["clb"];
            Club club = null;
            foreach (Club c in lst)
            {
                if (c.ClubId == id)
                {
                    club = c;
                    break;
                }
            }
            return club;
        }
        public void InsertClub(Club club)
        {
            List<Club> lst = (List<Club>)HttpContext.Current.Session["clb"];

            lst.Add(club);
            HttpContext.Current.Session["clb"] = lst;
        }
        




    }
}

SoccerClubManagementSystem/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SoccerClubManagementSystem.Models
{
    //This is Player Model
    public class Player
    {
        public int PlayerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Age { get; set; }
        public string Email { get; set; }
        public int JoinMonth { get; set; }
        public int JoinYear { get; set; }
        public int JoinDay { get; set; }


    }
}

SoccerClubManagementSystem/Controllers/ClubController.cs
using SoccerClubManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace SoccerClubManagementSystem.Controllers
{
    public class ClubController : Controller
    {
        private static int clubnumber = 103;
        //instance of repository 
        ClubRepository crepo = new ClubRepository();

        //This method load list of club using GetClub method of repository
        public ActionResult Index()
        {

            return View(crepo.GetClubs());
        }


        //This is get method for Addclub method 
        public ActionResult AddClub()
        {
            return View();
        }

        //This is post method for Addclub method 
        //This method add new Club to clublist 
        //using InsertCluub method
        [HttpPost]
        public ActionResult AddClub(Club club)
        {
            club.ClubId = Seq();

            crepo.InsertClub(club);
            return RedirectToAction("Index");
        }

        //This method display details of Club Single club
        public ActionResult Details(int id)
        {

            return View(crepo.GetClubByID(id));
        }

        //This is generating club id 
        int Seq()
        {
            return Interlocked.Increment(ref clubnumber);
        }
    }
}

SoccerClubManagementSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SoccerClubManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SoccerClubManagementSystem/Views/Club/AddClub.cshtml
@*
    
This is Addclub view
here We are loading partialview  using
@Html.Partial("_AddClubPartialView", Model)    
*@


@model SoccerClubManagementSystem.Models.Club
@{
    ViewBag.Title = "AddClub";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm("AddClub", "Club", FormMethod.Post))
{

    @Html.Partial("_AddClubPartialView", Model)

    <p>
        <input type="submit" value="Save" /> <input type="button" value="cancel" onclick="window.location.href='@Url.Action("Index", "Home")'" />
    </p>

}

SoccerClubManagementSystem/Views/Club/Details.cshtml
@model SoccerClubManagementSystem.Models.Club
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>@Model.ClubName  Details</h2>

<table id="clubs" style="width:300px;">
    <tr>
        <td>@Html.DisplayNameFor(model => model.ClubName)</td>
        <td>@Html.DisplayFor(model => model.ClubName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.ClubAddress)</td>
        <td>@Html.DisplayFor(model => model.ClubAddress)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.ClubCity)</td>
        <td>@Html.DisplayFor(model => model.ClubCity)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Clubcontact)</td>
        <td>@Html.DisplayFor(model => model.Clubcontact)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.ClubEmail)</td>
        <td>@Html.DisplayFor(model => model.ClubEmail)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.ClubContactPerson)</td>
        <td>@Html.DisplayFor(model => model.ClubContactPerson)</td>
    </tr>
</table>
@Html.ActionLink("Back to List", "Index")

SoccerClubManagementSystem/Views/Club/Index.cshtml
@*
This is view in Which we are displaying list of Club using partial view
Following line is loading partialview 
@Html.Partial("_ListClubPartialView", Model)
    
*@


@model IEnumerable<SoccerClubManagementSystem.Models.Club>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@Html.ActionLink("Add New Club", "AddClub")

@Html.Partial("_ListClubPartialView", Model)

SoccerClubManagementSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SoccerClubManagementSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SoccerClubManagementSystem/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SoccerClubManagementSystem/Views/Shared/_AddClubPartialView.cshtml
@model SoccerClubManagementSystem.Models.Club


@Html.ValidationSummary(true)

<fieldset>
    <legend>Add New Club</legend>

    <div class="editor-label">
        <label>Club Name</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.ClubName)
        @Html.ValidationMessageFor(model => model.ClubName)
    </div>

    <div class="editor-label">
        <label>Club Address</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.ClubAddress)
        @Html.ValidationMessageFor(model => model.ClubAddress)
    </div>

    <div class="editor-label">
        <label>Club Contact</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Clubcontact)
        @Html.ValidationMessageFor(model => model.Clubcontact)
    </div>

    <div class="editor-label">
        <label>Club Email</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.ClubEmail)
        @Html.ValidationMessageFor(model => model.ClubEmail)
    </div>

    <div class="editor-label">
        <label>Club Contact Person</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.ClubContactPerson)
        @Html.ValidationMessageFor(model => model.ClubContactPerson)
    </div>

    <div class="editor-label">
        <label>Club City</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.ClubCity)
        @Html.ValidationMessageFor(model => model.ClubCity)
    </div>


</fieldset>

SoccerClubManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Soccer Club Management System </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Soccer Club", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Club", "Index", "Club")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Soccer Club Management System.</p>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SoccerClubManagementSystem/Views/Shared/_ListClubPartialView.cshtml
@model IEnumerable<SoccerClubManagementSystem.Models.Club>

<table id="clubs">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>City</th>
        <th>Action</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ClubId</td>
            <td>@item.ClubName</td>
            <td>@item.ClubAddress</td>
            <td>@item.ClubCity</td>
            <td>

                @Html.ActionLink("Details", "Details", new { id = item.ClubId })
            </td>


        </tr>

    }




</table>